name: Deploy with GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout 'pages' branch
        uses: actions/checkout@v4
        with:
          ref: 'page'

      - run: rm -rf *

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: Move files
        run: |
          cp -r dist/* .
          rm -rf dist

      - name: Set up Git user
        run: |
          git config user.name "Anton Cherednichenko"
          git config user.email "anton@anton.eco"

      - name: Commit and push
        run: |
          git add -A
          git commit -m "Update pages branch [skip ci]" || exit 0
          git push origin HEAD:pages